name: xarray
channels:
  - conda-forge
dependencies:
  - bokeh>=2.0.0
  - cartopy
  - cf_xarray
  - dask
  - dask-labextension
  - distributed
  - fsspec
  - gcsfs
  - geoviews
  - gsw
  - hvplot
  - ipywidgets>=7.5
  - jupyter-server-proxy
  - jupyterlab>=2.0.0
  - matplotlib!=3.3.1
  - nbgitpuller
  - netcdf4
  - nodejs
  - notebook
  - numpy>=1.18.1
  - pandas
  - pip
  - pydap
  - python-graphviz
  - python=3.8
  - scipy>=1.3.0
  - zarr
  - pip:
    - expectexception
